### ISSUE TITLE
Panic in `Count(uncheckedIndex int) uint64` method

### ISSUE THREAD

**Issue by YZherebukh** [caio/go-tdigest#37]
Panic in `summary.go` line 94
Package version: v4.0.1

Reproduce

``` golang 
package main

import (
	"log"
	"math"

	"github.com/caio/go-tdigest/v4"
)

var encoded = []byte{0, 0, 0, 2, 64, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 30, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 57, 218, 228, 145, 56, 144, 220, 164, 56, 246, 147, 148, 56, 167, 59, 172, 56, 180, 63, 252, 56, 119, 157, 197, 57, 42, 128, 69, 57, 26, 153, 122, 57, 60, 221, 112, 57, 223, 74, 154, 58, 168, 175, 77, 58, 226, 81, 198, 57, 19, 110, 202, 57, 20, 193, 107, 56, 71, 76, 113, 57, 176, 14, 255, 58, 7, 158, 41, 58, 46, 137, 145, 58, 190, 168, 234, 58, 170, 231, 36, 58, 175, 69, 162, 59, 68, 160, 188, 59, 186, 27, 89, 127, 128, 0, 0, 255, 192, 0, 0, 255, 192, 0, 0, 1, 1, 1, 1, 2, 2, 4, 1, 4, 5, 7, 3, 4, 4, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 1, 1, 2, 1, 1, 1}

func main() {

	var avgCpuUseTDigest tdigest.TDigest
	err := avgCpuUseTDigest.FromBytes(encoded)
	if err != nil {
		log.Fatalf("fail to decode tdigest: %v", err)
	}
	log.Println(percentile(&avgCpuUseTDigest, 0.999))

}

func percentile(d *tdigest.TDigest, quantile float64) float64 {
	if d == nil {
		return 0
	}
	val := d.Quantile(quantile)
	if !math.IsNaN(val) {
		return val
	}

	return 0
}
```
Is there anything I can do to help to resolve this issue? What is expected behavior if index is out of boundaries? what can be the reason of this?

Trace
```
panic: runtime error: index out of range [30] with length 30
    goroutine 712 [running]:
github.com/caio/go-tdigest/v4.(*summary).Count(...)
/go/pkg/mod/github.com/caio/go-tdigest/v4@v4.0.1/summary.go:96 
github.com/caio/go-tdigest/v4.(*TDigest).Quantile(0x1?, 0x1?)
/go/pkg/mod/github.com/caio/go-tdigest/v4@v4.0.1/tdigest.go:119 +0x437         
```

**Comment by caio** [comment]
Hello,

Thanks a lot for the sample. Are you able to collect the actual values recorded via `tdigest.Add()`? The serialized digest is useful to know that something is wrong but not so much to diagnose the cause.

Here's what `tdigest.summary.means` contain after deser:

```
[0 0 0 0 0.00041750495438463986 0.0004865804803557694 0.000604157306952402 0.0006839002599008381 0.000769850128563121 0.0008288864519272465 0.000991488926956663 0.001138926516432548 0.0013190422068873886 0.0017449367769586388 0.003031899428606266 0.004758579631015891 0.004899182476947317 0.0050410468138579745 0.005088563302706461 0.005424368391686585 0.005941709292528685 0.006607516515941825 0.008062135508225765 0.009366021105961408 0.010703240368457045 0.013703543540032115 0.019383073165954556 +Inf NaN NaN]
```

I suspect those pesky special values at the end have something to do with it :)

Given that the means are such small values, I suspect this is a case of floating point math going bonkers with very small values. There isn't extensive checking for this is this library.

If you can get the actual values that were added we can figure out where it's going bad and evaluate a fix.

That being said, I'd recommend scaling the values you Add to the digest. The means being super small implies that you're adding tiny numbers - in general you don't want the difference between your measurements to be too small, otherwise you end up in floating point traps. e.g. For telemetry in the ms ranges I'd `tdigest.Add(200)`, not `tdigest.Add(0.2)` so that I stay far from zero.
